### ISSUE TITLE
Update Error to Version 8.1.3.0 

### ISSUE THREAD

**Issue by mesiah70** [owncloud/apps#2108]
I get the following Error, when I try to update the bitnami owncloud to Version 8.1.3.0
I've followed the instruction here and set the correct permissions:

https://wiki.bitnami.com/Applications/BitNami_ownCloud#How_to_upgrade_ownCloud.3f

Error code is:

/mnt/disk/data/updater_backup/8.1.3.0.zip extraction error.

**Comment by RealRancor** [comment]
@mesiah70 The issue tracker of the updater app is located here:

https://github.com/owncloud/updater/issues

There you can find a an existing issue:

https://github.com/owncloud/updater/issues/163

which seems to got fixed with https://github.com/owncloud/updater/pull/166

I think you can close this one yourself. If this is still an issue you probably need to manually upgrade to oC 8.2 like described in the documentation.

**Comment by mesiah70** [comment]
Hello RealRancor,

after changing the downloader.php under /opt/bitnami/apps/owncloud/htdocs/apps/updater/lib

I still get this error: 

ist Ihre Sicherung: /mnt/disk/data/updater_backup/8.0.3.4-d9073139

/mnt/disk/data/updater_backup/8.2.1.4.zip extraction error.

The owner of this file is daemon. So I cannot Update via updater.

I started the update as described here

Upgrading from the ownCloud admin panel

ownCloud already have installed the "Updater" app that allows you to upgrade ownCloud application from the admin panel directly. For security reasons, ownCloud files do not have write access for the web server user but that is required if you want to upgrade the application.

Before running the "Updater" app, run the following commands to change the owner of the files in your installation:
sudo chown -R daemon /opt/bitnami/apps/owncloud/htdocs
sudo chmod 644 /opt/bitnami/apps/owncloud/htdocs/.user.ini

Then run the upgrade process from the admin panel: "Admin" -> "Update center" and run the upgrade process.

If the upgrade works well, we strongly suggest to restore the permissions of your folder. 
sudo chown -R bitnami /opt/bitnami/apps/owncloud/htdocs
sudo chmod 444 /opt/bitnami/apps/owncloud/htdocs/.user.ini
sudo chown -R daemon /opt/bitnami/apps/owncloud/htdocs/config /opt/bitnami/apps/owncloud/htdocs/apps


Any Idea why it is not updating even you have changed the file. Please help

rgds

mesiah

**Comment by mesiah70** [comment]
I've changed the downloader.php to this:

<?php

/**
 * ownCloud - Updater plugin
 *
 * @author Victor Dubiniuk
 * @copyright 2012-2013 Victor Dubiniuk victor.dubiniuk@gmail.com
 *
 * This file is licensed under the Affero General Public License version 3 or
 * later.
 */

namespace OCA\Updater;

class Downloader {

	const PACKAGE_ROOT = 'owncloud';

	protected static $package;

	public static function getPackage($url, $version) {
		self::$package = self::getBackupBase() . $version;
		if (preg_match('/\.zip$/i', $url)) {
			$type = '.zip';
		} elseif (preg_match('/(\.tgz|\.tar\.gz)$/i', $url)) {
			$type = '.tgz';
		} elseif (preg_match('/\.tar\.bz2$/i', $url)) {
			$type = '.tar.bz2';
		} else {
			throw new \Exception('Unable to extract package ' . $url . ': unknown format');
		}
		
		self::$package = self::$package . $type;
		
		try {
			// Reuse already downloaded package
			if (!file_exists(self::$package)){
				$client = \OC::$server->getHTTPClientService()->newClient();
				$client->get($url, 
					[
						'save_to' => self::$package,
						'timeout' => 10*60,
					]
				);

				\OC::$server->getLogger()->debug(
					'Downloaded ' . filesize(self::$package) . ' bytes.',
					['app' => 'updater']
				);
			} else {
				\OC::$server->getLogger()->debug(
					'Use already downloaded package ' . self::$package . '. Size is ' . filesize(self::$package) . ' bytes.',
					['app' => 'updater']
				);
			}
			
			$extractDir = self::getPackageDir($version);
			Helper::mkdir($extractDir, true);

			$archive = \OC_Archive::open(self::$package);
			if (!$archive || !$archive->extract($extractDir)) {
				throw new \Exception(self::$package . " extraction error");
			}
			
		} catch (\Exception $e){
			\OC::$server->getLogger()->error('Retrieving ' . $url, ['app' => 'updater']);
			self::cleanUp($version);
			throw $e;
		}
		
		//  Prepare extracted data
		//  to have '3rdparty', 'apps' and 'core' subdirectories
		$baseDir = $extractDir. '/' . self::PACKAGE_ROOT;
		if (!file_exists($baseDir)){
			\OC::$server->getLogger()->error(
				'Expected fresh sources in ' . $baseDir . '. Nothing is found. Something is wrong with OC_Archive.',
				['app' => 'updater']
			);
			\OC::$server->getLogger()->error(
				$extractDir  . ' content: ' . implode(' ', scandir($extractDir)),
				['app' => 'updater']
				
			);
			if ($type === '.zip' && !extension_loaded('zip')){
				$l10n = \OC::$server->getL10N('updater');
				$hint = $l10n->t('Please ask your server administrator to enable PHP zip extension.');
			}
			throw new \Exception(self::$package . " extraction error. " . $hint);
		}

		include $baseDir . '/version.php';
		Helper::checkVersion($OC_Version, $OC_VersionString);

		$sources = Helper::getSources($version);
		rename($baseDir . '/' . Helper::THIRDPARTY_DIRNAME, $sources[Helper::THIRDPARTY_DIRNAME]);
		rename($baseDir . '/' . Helper::APP_DIRNAME, $sources[Helper::APP_DIRNAME]);
		rename($baseDir, $sources[Helper::CORE_DIRNAME]);
	}

	public static function cleanUp($version){
		Helper::removeIfExists(self::getPackageDir($version));
		Helper::removeIfExists(self::getTempBase());
	}
	
	public static function isClean($version){
		return !@file_exists(self::getPackageDir($version));
	}
	
	public static function getPackageDir($version) {
		return self::getTempBase() . $version;
	}
	
	protected static function getTempBase(){
		$app = new \OCA\Updater\AppInfo\Application();
		return $app->getContainer()->query('Config')->getTempBase();
	}
	
	protected static function getBackupBase(){
		$app = new \OCA\Updater\AppInfo\Application();
		return $app->getContainer()->query('Config')->getBackupBase();
	}
}

**Comment by mesiah70** [comment]
And this is the error on my error.log of my webserver

[Fri Jan 22 13:17:23.243232 2016] [proxy_fcgi:error] [pid 1914:tid 140512086398720] [client 93.90.138.20:64193] AH01071: Got error 'PHP message: PHP Fatal error:  Class 'OCA\\Updater\\AppInfo\\Application' not found in /opt/bitnami/apps/owncloud/htdocs/apps/updater/lib/downloader.php on line 114\n', referer: https://wolke7.pas-net.com/index.php/apps/updater/update.php

**Comment by RealRancor** [comment]
@mesiah70 Just see:

>  If this is still an issue you probably need to manually upgrade to oC 8.2 like described in the documentation.

**Comment by PVince81** [comment]
Please reopen if you're still having issues with the most recent versions.
